# fly.toml app configuration file generated for youtubeplayer-auth-api on 2025-05-12T18:38:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'youtubeplayer-auth-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    port = 5001 # 檢查的端口，與 internal_port 一致
    type = "http"
    path = "/healthz"
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"

[processes]
  app = "npm run start"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
